[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
std = "c11"
hide-symbols = true
include = [ "source/wren/include" ]

[build.cpp]
std = "c++23"
hide-symbols = true
include = [ "source/wren/include" ]

[embed-engine-wren]
plug = "plugins/embed-engine-wren"

[wn]
exe = "wn"
src = [ "wn", "wren/vm" ]
lang = "cpp"
dyn-libs = [ "nwge", "nwge_bndl", "nwge_cli", "SDL2" ]

[sample_game]
plug = "plugins/nwge/bundle"
src = "source/sample"
out = "target/sample.bndl"
